name: Build and Deploy Flask App to Azure

on:
  push:
    branches:
      - main  # trunk-based workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build Docker image
      run: |
        docker build -t yazilimacrfinal.azurecr.io/flaskapp:${{ github.sha }} .

    - name: Push image to ACR
      run: |
        az acr login --name yazilimacrfinal
        docker push yazilimacrfinal.azurecr.io/flaskapp:${{ github.sha }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: projectpython
        images: yazilimacrfinal.azurecr.io/flaskapp:${{ github.sha }}
