name: Build and Deploy Flask App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Login to ACR
      run: |
        echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login yazilimacrfinal.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

    - name: Build Docker Image with commit SHA tag
      run: |
        docker build -t yazilimacrfinal.azurecr.io/flaskapp:${{ github.sha }} .

    - name: Tag image as 'latest'
      run: |
        docker tag yazilimacrfinal.azurecr.io/flaskapp:${{ github.sha }} yazilimacrfinal.azurecr.io/flaskapp:latest

    - name: Push both tags to ACR
      run: |
        docker push yazilimacrfinal.azurecr.io/flaskapp:${{ github.sha }}
        docker push yazilimacrfinal.azurecr.io/flaskapp:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: projectpython
        images: yazilimacrfinal.azurecr.io/flaskapp:latest
